version: "3.1"
services:
  
  # mongo db
  mobile-learning-mongo:
    image: mongo
    container_name: mobile-learning-mongo
    environment:
      - MONGO_INITDB=mobilelearning
    ports:
      - 27017:27017
    expose:
      - 27017

  # java quarkus backend
  mobile-learning-backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
      # dockerfile: Dockerfile
    container_name: mobile-learning-backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mobile-learning-mongo
    environment:
      - MONGODB_HOST=mobile-learning-mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=mobilelearning
    volumes:
      - ./backend/src/main/resources/privateKey.pem:/deployments/privateKey.pem
      - ./backend/src/main/resources/publicKey.pem:/deployments/publicKey.pem
      - ./backend/src/main/resources/application.properties:/deployments/application.properties
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: "host"

  # flutter frontend (todo)

  # nginx reverse proxy
  mobile-learning-nginx:
    build: ./nginx
    container_name: mobile-learning-nginx
    environment:
      - MOBILE_LEARNING_BACKEND_URL=http://localhost:8080
    ports:
      - 80:80
    depends_on:
      - mobile-learning-backend
    network_mode: "host"