name: deploy-dev
on:
  push:
    branches:
      - dev
jobs:
  deploy-via-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY_DEV }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY_DEV }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.IP_DEV }} >> ~/.ssh/known_hosts
      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.USER_AND_IP_DEV }} 'cd /home/loco/team-learning && git pull && docker compose -f traefik.docker-compose.yml up -d'
